idf_component_register(SRCS "wifiap.c"
                    INCLUDE_DIRS "include"
                    REQUIRES esp_wifi nvs_flash esp_event)
// filepath: c:\Users\Agustina\Escritorio\sistemas-embebidos\Laboratorio_2c\components\wifiap\CMakeLists.txt
idf_component_register(SRCS "wifiap.c"
                       INCLUDE_DIRS "include")